In [273]:
import numpy as np

In [274]:
#1D numpy array - vector
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [275]:
print(type(a))

<class 'numpy.ndarray'>


In [276]:
#2D numpy array - matrix
b = np.array([[1,2,3],[4,5,6]])

In [277]:
print(b)

[[1 2 3]
 [4 5 6]]


In [278]:
#3D numpy array - 
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [279]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [280]:
#Data type
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [281]:
np.array([1,2,3,4],dtype=bool)

array([ True,  True,  True,  True])

In [282]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [283]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [284]:
#reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [285]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [ ]:
np.ones((3,4))

In [ ]:
np.zeros((4,3))

In [ ]:
np.mat((2,2))

In [ ]:
np.random.random((3,4))

In [ ]:
#lineaer space
np.linspace(-10,10,10)

In [ ]:
np.linspace(1,10,20)

In [ ]:
np.linspace(1,10,20,dtype=int)

In [ ]:
np.eye(3) #np.identity(3)

In [ ]:
#Numpy Attributes


In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)

In [ ]:
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
a1

In [ ]:
a2

In [ ]:
a3

In [ ]:
#no od dimensions
a1.ndim

In [ ]:
a2.ndim

In [ ]:
a3.ndim

In [ ]:
print(a3.shape)

In [ ]:
a3

In [ ]:
a3.size

In [ ]:
a2.size

In [ ]:
a1.itemsize

In [ ]:
a2.itemsize

In [ ]:
print(a1.dtype)

In [ ]:
a1



In [ ]:
#Array operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12).reshape(3,4)

In [ ]:
a1


In [ ]:
a2

In [ ]:
#scalar operation

In [ ]:
a1*2

In [ ]:
a1/2

In [ ]:
a1**2

In [ ]:
#relational operation 

In [ ]:
a2>5

In [ ]:
a2==15

In [ ]:
#vector operations

In [ ]:
a1

In [ ]:
a2

In [ ]:
a1*a2


In [ ]:
a2

In [ ]:
np.max(a2,axis=1)

In [ ]:
np.min(a2)

In [ ]:
np.sum(a2)

In [ ]:
np.prod(a2)

In [ ]:
np.mean(a2,axis=0)

In [ ]:
np.median(a2,axis=1)

In [ ]:
np.std(a2,axis=0)

In [ ]:
np.var(a2)

In [ ]:
a2

In [ ]:
np.sin(a2)

In [ ]:
#Dot Product

In [ ]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [ ]:
np.dot(a2,a3)

In [ ]:
np.round(np.random.random((3,4))*100)

In [ ]:
np.floor(np.random.random((3,4))*100)

In [8]:
np.ceil(np.random.random((3,4))*100)

NameError: name 'np' is not defined

In [10]:
import numpy as np

In [12]:
a1 = np.arange(10)


In [ ]:
#Indexing and Slicing

In [14]:
a2 = np.arange(12).reshape(3,4)

In [16]:
a3 = np.arange(8).reshape(2,2,2)

In [18]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a1[-1]

9

In [22]:
a1[0]

0

In [24]:
a1[3]

3

In [26]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a2[1,2]

6

In [30]:
a2[2,3]

11

In [32]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
a3[1,0,1]

5

In [36]:
a3[0]

array([[0, 1],
       [2, 3]])

In [38]:
a3[0,1,0]

2

In [40]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a1[2:5]

array([2, 3, 4])

In [44]:
a1[2:5:2]

array([2, 4])

In [46]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a2[0]

array([0, 1, 2, 3])

In [50]:
a2[0,:]

array([0, 1, 2, 3])

In [52]:
a2[:,2]

array([ 2,  6, 10])

In [54]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [56]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [58]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [60]:
a2[1,::3]

array([4, 7])

In [64]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [66]:
a3 = np.arange(27).reshape(3,3,3)

In [68]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [70]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [72]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [424]:
a3[0,1,:]

array([3, 4, 5])

In [426]:
a3[1,:,1]

array([10, 13, 16])

In [428]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [430]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [432]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [74]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [76]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [78]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [82]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [84]:
#Stacking

In [96]:
a4 = np.arange(12,24).reshape(3,4)

In [98]:
a4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [104]:
np.hstack(a4)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [112]:
np.vstack(a4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [126]:
np.hsplit(a4,4)

[array([[12],
        [16],
        [20]]),
 array([[13],
        [17],
        [21]]),
 array([[14],
        [18],
        [22]]),
 array([[15],
        [19],
        [23]])]

In [130]:
np.hsplit(a4,2)

[array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [147]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c = []

import time

start = time.time()

for i in range(len(a)):
     c.append(a[i]+b[i])

print(time.time()-start)

4.531491994857788


In [149]:
import numpy as np

In [151]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

start = time.time()
c = a+b

print(time.time()-start)

0.469616174697876


In [153]:
4.53/0.46

9.847826086956522

In [155]:
#Fancy Index

In [159]:
a = np.arange(12).reshape(4,3)

In [161]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [167]:
a[1,2]

5

In [169]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [171]:
a[::2]

array([[0, 1, 2],
       [6, 7, 8]])

In [173]:
b = np.arange(24).reshape(6,4)

In [175]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [182]:
a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [186]:
#boolean indexing


In [192]:
a = np.random.randint(1,100,24).reshape(6,4)

In [194]:
a

array([[44, 48, 11, 24],
       [52, 92, 78, 34],
       [64, 65, 69, 77],
       [ 3,  6, 13, 66],
       [72, 13, 99, 52],
       [92, 55, 67, 61]])

In [196]:
#find all  numbers greater than 50

In [198]:
a>50

array([[False, False, False, False],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [False, False, False,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [200]:
a[a>50]

array([52, 92, 78, 64, 65, 69, 77, 66, 72, 99, 52, 92, 55, 67, 61])

In [202]:
#find out even number

In [204]:
a

array([[44, 48, 11, 24],
       [52, 92, 78, 34],
       [64, 65, 69, 77],
       [ 3,  6, 13, 66],
       [72, 13, 99, 52],
       [92, 55, 67, 61]])

In [206]:
a[a%2==0]

array([44, 48, 24, 52, 92, 78, 34, 64,  6, 66, 72, 52, 92])

In [208]:
#find all number greater then 50 and equal

In [212]:
a[(a>50) & (a%2==0)]

array([52, 92, 78, 64, 66, 72, 52, 92])